// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjhjwDN2L-_ioleLzQ6aV2kCIIMEyacsA',
    appId: '1:481676565592:web:dc57b838206281a516be2d',
    messagingSenderId: '481676565592',
    projectId: 'kitsys-nop-commerce',
    authDomain: 'kitsys-nop-commerce.firebaseapp.com',
    storageBucket: 'kitsys-nop-commerce.appspot.com',
    measurementId: 'G-RGJRHJQLQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHQtiq4I-rzyxzSVPnPtBhMDw1UcfZNIY',
    appId: '1:481676565592:android:d9a4c60537214c1d16be2d',
    messagingSenderId: '481676565592',
    projectId: 'kitsys-nop-commerce',
    storageBucket: 'kitsys-nop-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjp_PlfsG_ZEu0KBQP4yiNqbzbVX5As3Y',
    appId: '1:481676565592:ios:36357e19928fc5f216be2d',
    messagingSenderId: '481676565592',
    projectId: 'kitsys-nop-commerce',
    storageBucket: 'kitsys-nop-commerce.appspot.com',
    iosBundleId: 'com.nopstation.nopcartFlutter',
  );

}